name: Ability Draft
description: A problem in the Ability Draft game mode

labels: ["ability-draft"]

body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What is the problem?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID (and possibly Timestamp)
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: true