name: Cosmetic Bug
description: A cosmetic item is missing particles, positioned wrong, etc.

labels: ["cosmetic"]

body:
  - type: input
    id: name
    attributes:
      label: Cosmetic Item Name
      placeholder: ex. Mask of Inscrutable Zeal
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What is the problem?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID
      placeholder: ex. 6575941888
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If you have any, paste them here!
    validations:
      required: false