name: Item Bug
description: An item behaves in a way it probably shouldn't!

labels: ["item"]

body:
  - type: input
    id: name
    attributes:
      label: Item name
      placeholder: ex. Blink Dagger
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What is the problem?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID and Timestamp
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: true