name: Other
description: The other templates don't fit your problem?

body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What is the problem?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID (and possibly Timestamp)
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If you have any, paste them here!
    validations:
      required: false