name: Incorrect tooltip
description: A tooltip is wrong in some way - typos, spell amp does not affect damage numbers, talent changes not showing, etc.

title: "Enter a short summary here!"
labels: ["tooltip"]

body:
  - type: input
    id: name
    attributes:
      label: Hero and spell
      placeholder: ex. Rubick - Spell steal
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What is the problem?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If you have any, paste them here!
    validations:
      required: false