name: Close inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "35 * * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 365
          days-before-issue-close: 90
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 365 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 90 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  